name: Saludo usando variables
run-name: variables
on: 
  workflow_dispatch
env: 
  DIA_DE_SEMANA: Lunes
jobs:
  saludo-variables:
    runs-on: ubuntu-latest
    env:
      SALUDO: Hola
    steps:
      - name: saludar
      - run: echo "$SALUDO, $NOMBRE . Hoy es $DIA_DE_SEMANA!"
        env:
          NOMBRE: Jesus

